# Build stage
FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Go app with optimizations
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /{{.ProjectName}} cmd/{{.ProjectName}}/main.go

# Run stage
FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /

COPY --from=builder /{{.ProjectName}} /{{.ProjectName}}
COPY --from=builder /app/.env .env

EXPOSE 8080

ENTRYPOINT ["/{{.ProjectName}}"]
